language: go

sudo: required
services:
  - docker

before_script:
  - echo "before_script"

script:
  # 这里编写测试代码的命令
  - echo "test code"
  - docker image build -t lkbuilder .

after_success:
  # 当代码测试通过后执行的命令
  #- docker image build -t lkbuilder .